application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "long_and_very_secret_key_needed_to_verify_message_integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "secret_token"
  timeout_milliseconds: 10000
